### ISSUE TITLE
Save output audio device after restart

### ISSUE THREAD

**Issue by tsk7mde** [SamDel/ChromeCast-Desktop-Audio-Streamer#145]
Hello,

Is it possible to permanently store the output device (audio) in the configuration so that the
default audio device is not used with every restart. 

Thanks

**Comment by SamDel** [comment]
The settings are saved and restored between sessions. The recording device is also restored at startup, and after startup it's automatically changed when the default recording device changes.

In 5.1 there is an issue restoring the device at startup (in some cases). It's fixed in [Setup 5.1.4.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/11693228/Setup.5.1.4.zip). I'm not sure about virtual devices, does it work for you?

**Comment by tsk7mde** [comment]
The issue has been resolved.
The audio device remains the same after restarting the application.
Thank you!
