### ISSUE TITLE
Stabilize connections and automatic restarts/recoveries

### ISSUE THREAD

**Issue by SamDel** [SamDel/ChromeCast-Desktop-Audio-Streamer#31]
- Sometimes a connection drops off-line
- Sometimes a automatic restart failes (LOAD_FAILED error) for one or two devices (not all) for @GrahamDLL when checking the 'Automatically start devices at startup' option and restarting the application.

**Comment by GrahamDLL** [comment]
I have started and stopped the app about twenty times and one device failed to start on about three of those starts.

I ran Resource Monitor throughout and I did not see excessive CPU or memory use.  I did not see that any values in Resource Monitor were different when a device failed to start.

I cannot see any common factor in the fails. I haven't a clue.

**Comment by SamDel** [comment]
In [1.9.68](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/2865971/Setup.1.9.68.zip) I do a retry when 'load failed'. Maybe that works!?

**Comment by GrahamDLL** [comment]
Started 15 times and the devices all started on each and every startup ... but they were not in sync ... Logs 029 and 030

[log029-030.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/2866446/log029-030.zip)

Windows resizing works well ... thank you.

Restart last used group worked well ... I did not try restart last used devices.  Thank you again.

Start when Windows starts kinda worked ... The app starts but gives and exceptions ... Logs 031 and 032 ...

[log031-032.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/2866454/log031-032.zip)

Overall a solid B

**Comment by SamDel** [comment]
I dropped the wrong file 😄, this is the real [Setup 1.9.68.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/2866519/Setup.1.9.68.zip) with the retry fix. Can you try that one as well? (Then I can make that version 2.0.)

I already started with the 2.0 issues in another branch. Odd that all devices started now, I don't think I changed anything there in the 2.0 branch. 
It looks like I have to wait till the soundcard is up and running that's why you get the exceptions. I only tried it once myself. We can test that one later.

**Comment by GrahamDLL** [comment]
1.9.68
Attached logs show ...

033 - All devices started but not in sync
034 - All devices started and are in sync
035 - 037 - Not all devices started.

Is it only me that has a problem with automatic start of all devices?  It may be that the problem is specific to my setup.  I will never use automatic start of all devices so it may be that you don't need to chase this problem if it is only me.

I expect that somebody that wants to automatically start all devices will be able to test this in future if you make any further changes.

[log033-037.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/2868923/log033-037.zip)

**Comment by SamDel** [comment]
It's retrying, but it doesn't fix the connection. 
I'm going to make a 2.0 release and spent my time on the new features!
