### ISSUE TITLE
Specific device keeps starting at startup even though it was closed at last program shutdown

### ISSUE THREAD

**Issue by dday4thedeceiver** [SamDel/ChromeCast-Desktop-Audio-Streamer#52]
I have a device doing this, with "Automatically start last used... " option checked (only). 

I'm using one group, which does start automatically as intended, and this single device comes along for the ride regardless. This is 2.4.0

**Comment by SamDel** [comment]
Can you check the 'DeviceState' of the single device in the 'user.config' file? 
It's in `'C:\Users\<username>\AppData\Local\ChromeCast\...'`. Maybe it appears twice!?

An easy fix is maybe to do a "Reset Settings' on the options tab. It also clears the list of known devices.

**Comment by dday4thedeceiver** [comment]
I manually deleted the devices from the config and restarted - now it's fixed.  Guess the devices get duplicated when their IP changes?

**Comment by SamDel** [comment]
This is fixed in [Setup 2.4.15.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/3674285/Setup.2.4.15.zip). The device was restarting because of a bug in saving the known devices. See also [this](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/54) issue.

Please reopen if it still occurs.
